// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGckabqlj4bMgLZLLRXaqlL33qqqpObpI',
    appId: '1:1047168315852:web:8167968461dfb43ec36d69',
    messagingSenderId: '1047168315852',
    projectId: 'carfinderapp-22596',
    authDomain: 'carfinderapp-22596.firebaseapp.com',
    storageBucket: 'carfinderapp-22596.appspot.com',
    measurementId: 'G-HVS6SNZ3WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDufYnlnCwRg0sL98rsfTqf2CuaeSSAqok',
    appId: '1:1047168315852:android:992aedd894c52620c36d69',
    messagingSenderId: '1047168315852',
    projectId: 'carfinderapp-22596',
    storageBucket: 'carfinderapp-22596.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh_EWXiUGKRqhGq-0afzjhhfCUVsoiUV4',
    appId: '1:1047168315852:ios:b3f6af261f99e598c36d69',
    messagingSenderId: '1047168315852',
    projectId: 'carfinderapp-22596',
    storageBucket: 'carfinderapp-22596.appspot.com',
    androidClientId: '1047168315852-5fq4pl8e8sus7q2713sshvp1oibp8r5s.apps.googleusercontent.com',
    iosClientId: '1047168315852-jbf272o81jgdaeusgdfov6dq3demlu63.apps.googleusercontent.com',
    iosBundleId: 'com.example.carAppFinderMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh_EWXiUGKRqhGq-0afzjhhfCUVsoiUV4',
    appId: '1:1047168315852:ios:b3f6af261f99e598c36d69',
    messagingSenderId: '1047168315852',
    projectId: 'carfinderapp-22596',
    storageBucket: 'carfinderapp-22596.appspot.com',
    androidClientId: '1047168315852-5fq4pl8e8sus7q2713sshvp1oibp8r5s.apps.googleusercontent.com',
    iosClientId: '1047168315852-jbf272o81jgdaeusgdfov6dq3demlu63.apps.googleusercontent.com',
    iosBundleId: 'com.example.carAppFinderMobile',
  );
}
